from __future__ import annotations

import json
from copy import deepcopy
from pathlib import Path


DEFAULT_PAYLOAD = {
    "schemaVersion": 1,
    "project": "game1",
    "profiles": [
        {
            "targetType": "character",
            "targetId": "human_female",
            "displayName": "Human Female",
            "rules": [
                {
                    "channel": "run",
                    "label": "Run Speed",
                    "stat": "RunSpeed",
                    "unitsPerPercent": 2.0,
                },
                {
                    "channel": "walk",
                    "label": "Walk Speed",
                    "stat": "RunSpeed",
                    "unitsPerPercent": 4.0,
                },
                {
                    "channel": "combat_idle",
                    "label": "Idle Combat Speed",
                    "stat": "AttackSpeed",
                    "unitsPerPercent": 2.0,
                },
                {
                    "channel": "attack",
                    "label": "Attack Speed",
                    "stat": "AttackSpeed",
                    "unitsPerPercent": 2.0,
                },
            ],
        },
        {
            "targetType": "monster",
            "targetId": "gremlin",
            "displayName": "Gremlin",
            "rules": [
                {
                    "channel": "run",
                    "label": "Run Speed",
                    "stat": "RunSpeed",
                    "unitsPerPercent": 0.6,
                },
            ],
        },
    ],
}


class AnimationSpeedScalingStore:
    def __init__(self, root: Path):
        self.root = Path(root)
        self.manifest_path = self.root / "assets/manifests/animation-speed-scaling.json"
        self.registry_path = self.root / "src/shared/animation/AnimationSpeedScalingRegistry.luau"
        self._ensure()

    def _ensure(self):
        if not self.manifest_path.is_file():
            payload = deepcopy(DEFAULT_PAYLOAD)
            self._write(payload)
        else:
            payload = self._read()
            self._validate(payload)
            self._write_registry(payload)

    def _read(self) -> dict:
        return json.loads(self.manifest_path.read_text(encoding="utf-8"))

    def _validate(self, payload: dict):
        if int(payload.get("schemaVersion") or 0) != 1:
            raise ValueError("unsupported animation speed scaling schema")
        profiles = payload.get("profiles")
        if not isinstance(profiles, list):
            raise ValueError("animation speed scaling profiles must be a list")
        seen = set()
        for profile in profiles:
            target_type = str(profile.get("targetType") or "").strip().lower()
            target_id = str(profile.get("targetId") or "").strip().lower()
            if target_type not in {"character", "monster"} or not target_id:
                raise ValueError("invalid animation speed scaling target")
            rules = profile.get("rules")
            if not isinstance(rules, list) or not rules:
                raise ValueError(f"animation speed scaling target {target_id} has no rules")
            for rule in rules:
                channel = str(rule.get("channel") or "").strip().lower()
                stat = str(rule.get("stat") or "").strip()
                key = (target_type, target_id, channel)
                if not channel or not stat or key in seen:
                    raise ValueError("invalid or duplicate animation speed scaling rule")
                seen.add(key)
                units = float(rule.get("unitsPerPercent") or 0)
                if not (0.001 <= units <= 100000):
                    raise ValueError("units per 1% must be between 0.001 and 100000")

    @staticmethod
    def _lua_string(value: str) -> str:
        return json.dumps(str(value), ensure_ascii=False)

    @staticmethod
    def _lua_number(value: float) -> str:
        text = format(float(value), ".12g")
        return text if "." in text else text + ".0"

    def _write_registry(self, payload: dict):
        grouped: dict[str, dict[str, dict]] = {"character": {}, "monster": {}}
        for profile in payload.get("profiles") or []:
            target_type = str(profile["targetType"]).lower()
            target_id = str(profile["targetId"]).lower()
            rules = {}
            for rule in profile.get("rules") or []:
                rules[str(rule["channel"]).lower()] = {
                    "stat": str(rule["stat"]),
                    "unitsPerPercent": float(rule["unitsPerPercent"]),
                }
            grouped[target_type][target_id] = rules

        lines = [
            "-- generated by Asset Manager. do not edit by hand.",
            "return table.freeze({",
            "\tschemaVersion = 1,",
            '\tproject = "game1",',
            "\tprofiles = table.freeze({",
        ]
        for target_type in ("character", "monster"):
            lines.append(f"\t\t[{self._lua_string(target_type)}] = table.freeze({{")
            for target_id in sorted(grouped[target_type]):
                lines.append(f"\t\t\t[{self._lua_string(target_id)}] = table.freeze({{")
                for channel in sorted(grouped[target_type][target_id]):
                    rule = grouped[target_type][target_id][channel]
                    lines += [
                        f"\t\t\t\t[{self._lua_string(channel)}] = table.freeze({{",
                        f"\t\t\t\t\tstat = {self._lua_string(rule['stat'])},",
                        f"\t\t\t\t\tunitsPerPercent = {self._lua_number(rule['unitsPerPercent'])},",
                        "\t\t\t\t}),",
                    ]
                lines.append("\t\t\t}),")
            lines.append("\t\t}),")
        lines += ["\t}),", "})", ""]
        self.registry_path.parent.mkdir(parents=True, exist_ok=True)
        self.registry_path.write_text("\n".join(lines), encoding="utf-8")

    def _write(self, payload: dict):
        self._validate(payload)
        self.manifest_path.parent.mkdir(parents=True, exist_ok=True)
        self.manifest_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        self._write_registry(payload)

    def snapshot(self) -> dict:
        payload = self._read()
        self._validate(payload)
        return payload

    def update(self, request: dict) -> dict:
        target_type = str(request.get("targetType") or "").strip().lower()
        target_id = str(request.get("targetId") or "").strip().lower()
        channel = str(request.get("channel") or "").strip().lower()
        units = float(request.get("unitsPerPercent") or 0)
        if not (0.001 <= units <= 100000):
            raise ValueError("units per 1% must be between 0.001 and 100000")

        payload = self._read()
        found = False
        for profile in payload.get("profiles") or []:
            if str(profile.get("targetType") or "").lower() != target_type:
                continue
            if str(profile.get("targetId") or "").lower() != target_id:
                continue
            for rule in profile.get("rules") or []:
                if str(rule.get("channel") or "").lower() == channel:
                    rule["unitsPerPercent"] = units
                    found = True
                    break
        if not found:
            raise ValueError("unknown animation speed scaling rule")
        self._write(payload)
        return payload
