from __future__ import annotations

import json
from copy import deepcopy
from pathlib import Path


DEFAULT_PAYLOAD = {
    "schemaVersion": 1,
    "project": "game1",
    "combat": {
        "stateDurationSeconds": 6.0,
    },
    "characterAnimations": {
        "deathPlaybackPercent": 100.0,
        "revivePlaybackPercent": 100.0,
    },
}


class OptionsStore:
    def __init__(self, root: Path):
        self.root = Path(root)
        self.manifest_path = self.root / "assets/manifests/options.json"
        self.registry_path = self.root / "src/shared/GameOptionsRegistry.luau"
        self._ensure()

    def _read(self) -> dict:
        return json.loads(self.manifest_path.read_text(encoding="utf-8"))

    def _validate(self, payload: dict):
        if int(payload.get("schemaVersion") or 0) != 1:
            raise ValueError("unsupported options schema")
        combat = payload.get("combat") or {}
        duration = float(combat.get("stateDurationSeconds") or 0)
        if not (0 <= duration <= 3600):
            raise ValueError("combat state duration must be 0..3600 seconds")
        animations = payload.get("characterAnimations") or {}
        for key in ("deathPlaybackPercent", "revivePlaybackPercent"):
            percent = float(animations.get(key) or 0)
            if not (1 <= percent <= 400):
                raise ValueError(f"{key} must be 1..400 percent")

    def _write_registry(self, payload: dict):
        combat = payload["combat"]
        animations = payload["characterAnimations"]
        lines = [
            "-- generated by Asset Manager. do not edit by hand.",
            "return table.freeze({",
            "\tschemaVersion = 1,",
            '\tproject = "game1",',
            "\tcombat = table.freeze({",
            f"\t\tstateDurationSeconds = {float(combat['stateDurationSeconds']):.12g},",
            "\t}),",
            "\tcharacterAnimations = table.freeze({",
            f"\t\tdeathPlaybackPercent = {float(animations['deathPlaybackPercent']):.12g},",
            f"\t\trevivePlaybackPercent = {float(animations['revivePlaybackPercent']):.12g},",
            "\t}),",
            "})",
            "",
        ]
        self.registry_path.parent.mkdir(parents=True, exist_ok=True)
        self.registry_path.write_text("\n".join(lines), encoding="utf-8")

    def _write(self, payload: dict):
        self._validate(payload)
        self.manifest_path.parent.mkdir(parents=True, exist_ok=True)
        self.manifest_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        self._write_registry(payload)

    def _ensure(self):
        if not self.manifest_path.is_file():
            self._write(deepcopy(DEFAULT_PAYLOAD))
            return
        payload = self._read()
        changed = False
        for group, defaults in (("combat", DEFAULT_PAYLOAD["combat"]), ("characterAnimations", DEFAULT_PAYLOAD["characterAnimations"])):
            if not isinstance(payload.get(group), dict):
                payload[group] = {}
                changed = True
            for key, value in defaults.items():
                if key not in payload[group]:
                    payload[group][key] = value
                    changed = True
        if changed:
            payload["schemaVersion"] = 1
            payload["project"] = "game1"
            self._write(payload)
        else:
            self._validate(payload)
            self._write_registry(payload)

    def snapshot(self) -> dict:
        payload = self._read()
        self._validate(payload)
        return payload

    def update(self, request: dict) -> dict:
        payload = self._read()
        combat = request.get("combat")
        if isinstance(combat, dict) and "stateDurationSeconds" in combat:
            payload.setdefault("combat", {})["stateDurationSeconds"] = float(combat["stateDurationSeconds"])
        animations = request.get("characterAnimations")
        if isinstance(animations, dict):
            for key in ("deathPlaybackPercent", "revivePlaybackPercent"):
                if key in animations:
                    payload.setdefault("characterAnimations", {})[key] = float(animations[key])
        self._write(payload)
        return payload
